---
abstract: 'Perl interface to Skype.framework'
author:
  - 'Daisuke Murase <typester@cpan.org>'
build_requires:
  Devel::PPPort: 3.19
  ExtUtils::MakeMaker: 6.36
  Test::More: 0.88
configure_requires:
  Devel::PPPort: 3.19
  ExtUtils::MakeMaker: 6.36
  ExtUtils::ParseXS: 2.21
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Cocoa-Skype
no_index:
  directory:
    - example
    - inc
    - share
    - t
    - xt
requires:
  File::ShareDir: 0
  XSLoader: 0.02
resources:
  license: http://dev.perl.org/licenses/
version: 0.03
